export * from './start.js'
export * from './main_menu.js'
export * from './menu_buyurtma_berish.js'
export * from './on_contact.js'
export * from './settings.js'
export * from './yangi_buyurtma.js'
export * from './buyurtma_kurish.js'
export * from './on_message.js'
